# Constants, remove some of these when implementing the Settings menu.
CELL_SIZE = 32
CELL_NUMBER = 20
BG = "#8fbc47"
FG = "#233c1e"
BOARD_LENGTH = CELL_SIZE * CELL_NUMBER
MAX_LENGTH = 3 * BOARD_LENGTH - 1
MAX_ENERGY = 4 * CELL_NUMBER
V_BOUNDARIES = 3 * CELL_SIZE
H_BOUNDARIES = 2 * CELL_SIZE
HEIGHT = BOARD_LENGTH + 2 * V_BOUNDARIES
WIDTH = BOARD_LENGTH + 2 * H_BOUNDARIES
FONT_PATH = "app/assets/font/pixel-font-4x4.otf"
